[prompt]
format = "$all"

[[battery.display]] # バッテリー残量が0％〜10％の間は「太字の赤色」スタイルを利用する
threshold = 10
style = "bold red"

[character]
success_symbol = "[➜](bold green) "     # 「success_symbol」セグメントは「ボールドグリーン」の色で「➜」に設定されています
error_symbol = "[➜](bold red) "
vicmd_symbol = "[V](bold green) "

